Repository Azure/terraform-azurerm-avm-res-storage-storageaccount, pull requests merged in 2024-05, with the labels that each got.

#70 Critical Update on Storage Module
  .github/CODEOWNERS
  .github/workflows/e2e.yml
  .github/workflows/linting.yml
  .github/workflows/version-check.yml
  README.md
  _header.md
  examples/customer-managed-key/README.md
  examples/customer-managed-key/main.tf
  examples/customer-managed-key/variables.tf
  examples/default/README.md
  examples/default/main.tf
  examples/default/variables.tf
  examples/diagnostic-settings/README.md
  examples/diagnostic-settings/main.tf
  examples/diagnostic-settings/variables.tf
  examples/private-endpoint/README.md
  examples/private-endpoint/main.tf
  examples/private-endpoint/variables.tf
  examples/role_assignments/README.md
  examples/role_assignments/main.tf
  examples/role_assignments/variables.tf
  locals.tf
  main.containers.tf
  main.locks.tf
  main.privateendpoint.tf
  main.tf
  outputs.tf
  variables.storageaccount.tf
  variables.tf
Labels: Needs: Triage :mag:

#97 Update access_tier according to latest AzARM release
  main.tf
Labels: Needs: Triage :mag:

#101 Dev privateendpoint
  examples/private-endpoint-Staticip/README.md
  examples/private-endpoint-Staticip/_footer.md
  examples/private-endpoint-Staticip/_header.md
  examples/private-endpoint-Staticip/main.tf
  examples/private-endpoint-Staticip/variables.tf
Labels: Needs: Triage :mag:, Status: Fixed :white_check_mark:

#103 Update diagnostic settings vars
  README.md
  examples/diagnostic-settings/README.md
  examples/diagnostic-settings/main.tf
  locals.version.tf.json
  main.diagnostics.tf
  variables.diagnostics.tf
Labels: Status: In PR :point_right:, Language: Terraform :globe_with_meridians:

#102 Rename the examples folder
  examples/private-endpoint-static-ip/README.md
  examples/private-endpoint-static-ip/_footer.md
  examples/private-endpoint-static-ip/_header.md
  examples/private-endpoint-static-ip/main.tf
  examples/private-endpoint-static-ip/variables.tf
Labels: Needs: Triage :mag:
